{
 "title": "Mind the Gap",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Items",
    "query": "select distinct name from rs_buys"
   }
  ]
 },
 "panels": [
  { "title": "Market Dynamics of $Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Items" },
  {
   "title": "Bid and Ask Spread of $Items",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "highTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,\n    avg(high)\nFROM $table\n\nWHERE $timeFilter and name in ($Items)\n\nGROUP BY t, name\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(highTime), 1) * 1) * 1000 as t,\n    name,\n    avg(high)\nFROM default.rs_buys\n\nWHERE highTime >= toDateTime(1692231374) AND highTime <= toDateTime(1692231674) and name in ('Coconut')\n\nGROUP BY t, name\n\nORDER BY t",
     "round": "0s",
     "table": "rs_buys"
    },
    {
     "database": "default",
     "dateTimeColDataType": "lowTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,\n    avg(low)\nFROM $table\n\nWHERE $timeFilter and name in ($Items)\n\nGROUP BY t, name\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(lowTime), 1) * 1) * 1000 as t,\n    name,\n    avg(low)\nFROM default.rs_sells\n\nWHERE lowTime >= toDateTime(1692231374) AND lowTime <= toDateTime(1692231674) and name in ('Coconut')\n\nGROUP BY t, name\n\nORDER BY t",
     "round": "0s",
     "table": "rs_sells"
    }
   ]
  },
  {
   "title": "$Items Low Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "lowTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    lowTime,\n    low\nFROM $table\n\nWHERE name = $Items\n\nORDER BY lowTime DESC\n\nLIMIT 1 \n",
     "rawQuery": "SELECT\n    lowTime,\n    low\nFROM default.rs_sells\n\nWHERE name = 'Coconut'\n\nORDER BY lowTime DESC\n\nLIMIT 1",
     "round": "0s",
     "table": "rs_sells"
    }
   ]
  },
  {
   "title": "$Items High Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "highTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    highTime,\n    high\n    \nFROM $table\n\nWHERE name = $Items\n\nORDER BY highTime DESC\n\nLIMIT 1 \n",
     "rawQuery": "SELECT\n    highTime,\n    high\n    \nFROM default.rs_buys\n\nWHERE name = 'Coconut'\n\nORDER BY highTime DESC\n\nLIMIT 1",
     "round": "0s",
     "table": "rs_buys"
    }
   ]
  },
  {
   "title": "$Items Potential Profit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUInt64(highTime) + toUInt64(lowTime) as AggTime,\n    (high - (high * .01)) - low as profit\nFROM rs_sells\nJOIN rs_buys ON rs_sells.id = rs_buys.id\nWHERE  rs_sells.name = $Items AND rs_buys.name = $Items AND rs_buys.highTime > now() - interval 15 minute and rs_sells.lowTime > now() - interval 15 minute\nORDER BY AggTime DESC\nLIMIT 1\n",
     "rawQuery": "SELECT\n    toUInt64(highTime) + toUInt64(lowTime) as AggTime,\n    (high - (high * .01)) - low as profit\nFROM rs_sells\nJOIN rs_buys ON rs_sells.id = rs_buys.id\nWHERE  rs_sells.name = 'Dynamite' AND rs_buys.name = 'Dynamite' AND rs_buys.highTime > now() - interval 15 minute and rs_sells.lowTime > now() - interval 15 minute\nORDER BY AggTime DESC\nLIMIT 1",
     "round": "0s"
    }
   ]
  }
 ]
}