create-dev:
	pip install poetry==1.4.2
	python3 -m poetry install
test:
	poetry run pytest --cov-report term --cov-report html --cov=./runespreader .
format-check:
	poetry run black --check .
	poetry run isort --check .